// 事件卡牌配置
//
// 这个文件只放卡牌数据，方便非工程同事调整文案、金额、持续时间和选项。
// 主游戏逻辑在 script.js；新增 effect 类型前，请先确认 script.js 里有对应处理逻辑。

var eventCards = [
  {
    id: "kids_classes",
    title: "孩子报课外班",
    category: "expense_up",
    description: "孩子新增课外班，每月支出增加 2000 元，持续 6 个月。",
    effect: { type: "add_active_effect", target: "expense", amount: 2000, duration: 6 },
    insight: "这笔支出会持续几个月。",
  },
  {
    id: "rent_up",
    title: "房租上涨",
    category: "expense_up",
    description: "房租续约时，房东提出租金上涨约 5%。你可以续租，也可以搬家。",
    choices: [
      {
        label: "继续续租",
        resultText: "接受涨租，常规月支出增加约 5%。",
        effect: { type: "add_active_effect", target: "expense_percent", amount: 0.05, duration: 999 },
      },
      {
        label: "搬一次家",
        resultText: "支付搬家和周转费用，避开这次涨租。",
        effect: { type: "change_savings", amount: -5000 },
      },
    ],
    insight: "房租续约已经处理。",
  },
  {
    id: "parents_support",
    title: "父母生活支持增加",
    category: "expense_up",
    description: "家里老人需要更多生活支持，常规月支出增加约 8%，持续 6 个月。",
    effect: { type: "add_active_effect", target: "expense_percent", amount: 0.08, duration: 6 },
    insight: "家庭支持增加了月支出。",
  },
  {
    id: "childcare_cost",
    title: "育儿支出增加",
    category: "expense_up",
    description: "家庭育儿支出增加，常规月支出增加约 10%，持续 12 个月。",
    effect: { type: "add_active_effect", target: "expense_percent", amount: 0.1, duration: 12 },
    insight: "育儿支出进入了接下来一段时间的账单。",
  },
  {
    id: "elder_hospital",
    title: "老人住院",
    category: "one_time_cost",
    description: "家里老人突发住院，自付医疗支出 50000 元。",
    effect: { type: "change_savings", amount: -50000 },
    insight: "这笔支出直接消耗现金储备。",
  },
  {
    id: "car_repair",
    title: "车辆维修",
    category: "one_time_cost",
    description: "车子出现故障，可以完整维修，也可以先处理影响使用的关键部件。",
    choices: [
      {
        label: "完整维修",
        resultText: "一次把这次发现的故障处理完。",
        effect: { type: "change_savings", amount: -4500 },
      },
      {
        label: "先修关键部件",
        resultText: "先恢复正常使用，剩余问题以后再处理。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -1800 },
            {
              type: "schedule_savings_effect",
              id: "car_repair_follow_up",
              triggerDelay: 4,
              preserveDelay: true,
              amount: -3000,
              title: "车辆再次维修",
              message: "之前只修了关键部件，剩余故障这次需要处理。",
            },
          ],
        },
      },
    ],
    insight: "车辆故障已经处理。",
  },
  {
    id: "moving_cost",
    title: "搬家支出",
    category: "one_time_cost",
    description: "因为工作或家庭原因搬家，搬运和杂费合计 5000 元。",
    effect: { type: "change_savings", amount: -5000 },
    insight: "搬家带来一次性支出。",
  },
  {
    id: "home_appliance",
    title: "某个家电出现故障",
    category: "one_time_cost",
    description: "家里一台常用家电突然出现故障。现在可以维修，也可以趁政府补贴换新。",
    choices: [
      {
        label: "花 1,000 元维修",
        resultText: "先把坏掉的家电修好。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -1000 },
            {
              type: "schedule_savings_effect",
              id: "home_appliance_breaks_again",
              triggerDelay: 3,
              preserveDelay: true,
              amount: -5000,
              title: "家电又坏了",
              message: "三个月前维修过的家电再次出现故障，这次需要花 5,000 元换新。",
            },
          ],
        },
      },
      {
        label: "趁补贴购入新家电",
        resultText: "原价 5,000 元，政府补贴后实际支付 4,000 元。",
        effect: { type: "change_savings", amount: -4000 },
      },
    ],
    insight: "家电故障已经处理。",
  },
  {
    id: "property_fee_up",
    title: "夏季电费上涨",
    category: "expense_up",
    description: "夏天常开空调，电费明显变高，每月支出增加 500 元，持续 3 个月。",
    effect: { type: "add_active_effect", target: "expense", amount: 500, duration: 3 },
    insight: "这是短期季节性支出。",
  },
  {
    id: "commute_cost_up",
    title: "通勤成本增加",
    category: "expense_up",
    description: "工作地点调整后，通勤距离变远，常规月支出增加 400 元。",
    effect: { type: "add_active_effect", target: "expense", amount: 400, duration: 999 },
    insight: "通勤成本变成长期支出。",
  },
  {
    id: "nanny_help",
    title: "临时请人照护",
    category: "expense_up",
    description: "家里需要临时请人帮忙照护，常规月支出增加约 10%，持续 4 个月。",
    effect: { type: "add_active_effect", target: "expense_percent", amount: 0.1, duration: 4 },
    insight: "照护支出会持续几个月。",
  },
  {
    id: "phone_replacement",
    title: "手机突然报废",
    category: "one_time_cost",
    description: "手机突然报废，工作和生活都离不开，只能立刻更换，一次性支出 5000 元。",
    effect: { type: "change_savings", amount: -5000 },
    insight: "设备更换消耗现金储备。",
  },
  {
    id: "wedding_gift",
    title: "集中人情往来",
    category: "one_time_cost",
    description: "这个月婚礼、满月和探望集中出现，人情往来一次性支出 3200 元。",
    effect: { type: "change_savings", amount: -3200 },
    insight: "人情往来集中到这个月。",
  },
  {
    id: "pipe_leak",
    title: "家里漏水维修",
    category: "one_time_cost",
    description: "家中水管或龙头漏水，需要上门维修，一次性支出 800 元。",
    effect: { type: "change_savings", amount: -800 },
    insight: "小额维修已经结清。",
  },
  {
    id: "wedding_travel",
    title: "朋友婚礼出行",
    category: "one_time_cost",
    description: "你去外地参加朋友婚礼，交通、住宿和礼金合计支出 2800 元。",
    effect: { type: "change_savings", amount: -2800 },
    insight: "这笔人情出行已经结清。",
  },
  {
    id: "pet_clinic",
    title: "宠物看病",
    category: "one_time_cost",
    description: "家里的宠物临时看病，一次性支出 1800 元。",
    effect: { type: "change_savings", amount: -1800 },
    insight: "宠物医疗支出已经结清。",
  },
  {
    id: "laptop_repair",
    title: "电脑维修",
    category: "one_time_cost",
    description: "电脑突然故障，需要更换配件和维修，一次性支出 2200 元。",
    effect: { type: "change_savings", amount: -2200 },
    insight: "维修费从现金储备里支出。",
  },
  {
    id: "holiday_spending",
    title: "节日开销",
    category: "one_time_cost",
    description: "节日期间聚餐、礼物和交通集中出现，一次性支出 2600 元。",
    effect: { type: "change_savings", amount: -2600 },
    insight: "节日开销集中到这个月。",
  },
  {
    id: "relatives_visit",
    title: "亲戚来住一阵",
    category: "expense_up",
    description: "家里亲戚来住一阵，伙食和日用品支出增加，每月支出增加 800 元，持续 2 个月。",
    effect: { type: "add_active_effect", target: "expense", amount: 800, duration: 2 },
    insight: "家里临时多了一段支出。",
  },
  {
    id: "gym_renewal_choice",
    title: "健身年卡续费",
    category: "choice",
    description: "健身房年卡到期，你可以续费，也可以先暂停。",
    choices: [
      {
        label: "续一年",
        resultText: "你支付 2500 元续费年卡。",
        effect: { type: "change_savings", amount: -2500 },
      },
      {
        label: "先暂停",
        resultText: "你暂时不续费，也暂停了原本的运动安排。",
        wellbeingCost: 2,
        wellbeingReason: "暂停了原本的运动安排",
        effect: { type: "none" },
      },
    ],
    insight: "健身卡已经处理。",
  },
  {
    id: "salary_cut",
    title: "公司业务调整",
    category: "income_down",
    description: "公司业务调整，你的收入先下降 30%。什么时候恢复，公司没有给明确时间。",
    effect: {
      type: "add_uncertain_active_effect",
      target: "income_percent",
      amount: -0.3,
      minMonths: 2,
      recoveryChance: 0.25,
      maxMonths: 12,
      recoveryText: "公司业务逐步恢复，你的收入回到原来的水平。",
    },
    insight: "收入下降，恢复时间不确定。",
  },
  {
    id: "bonus_cancelled",
    title: "绩效奖金缩水",
    category: "income_down",
    description: "这个月绩效和项目奖金都不理想，工资正常发放，但本月收入减少约 25%。",
    effect: { type: "one_month_income_percent", amount: -0.25 },
    insight: "本月浮动收入减少。",
  },
  {
    id: "project_delay",
    title: "项目奖金延期",
    category: "income_down",
    description: "一笔相当于月收入 60% 的项目奖金延期发放。你可以继续等待，也可以折价提前结算。",
    choices: [
      {
        label: "等待全部奖金",
        resultText: "本月暂不到账，两个月后再看回款结果。",
        hideImpact: true,
        effect: {
          type: "schedule_random_savings_effect",
          id: "project_delay_balance",
          triggerDelay: 2,
          preserveDelay: true,
          title: "延期项目奖金结果",
          outcomes: [
            {
              id: "recovered_after_lawsuit",
              weight: 0.5,
              incomePercent: 0.45,
              message: "支付相当于月收入 15% 的诉讼与材料费后，追回了全部项目奖金。",
            },
            {
              id: "paid_in_full",
              weight: 0.5,
              incomePercent: 0.6,
              message: "项目回款恢复正常，相当于月收入 60% 的奖金到账。",
            },
          ],
        },
      },
      {
        label: "折价提前结算",
        resultText: "本月立即收到相当于月收入 40% 的奖金，之后不再追讨剩余部分。",
        effect: { type: "change_savings_by_income_percent", amount: 0.4 },
      },
    ],
    insight: "这笔项目奖金已经处理。",
  },
  {
    id: "temporary_unemployment",
    title: "短期失业",
    category: "income_down",
    description: "从本月起暂时没有工作收入，收入归零，持续 2 个月。",
    effect: { type: "add_active_effect", target: "income_percent", amount: -1, duration: 2 },
    insight: "短期收入中断。",
  },
  {
    id: "commission_slowdown",
    title: "提成到账变慢",
    category: "income_down",
    description: "客户付款周期拉长，本月提成少到账，本月收入减少约 25%。",
    effect: { type: "one_month_income_percent", amount: -0.25 },
    insight: "本月提成到账减少。",
  },
  {
    id: "unpaid_leave",
    title: "临时无薪假",
    category: "income_down",
    description: "因为家庭安排，你本月请了几天无薪假，收入减少约 18%。",
    effect: { type: "one_month_income_percent", amount: -0.18 },
    insight: "本月收入减少。",
  },
  {
    id: "client_budget_cut",
    title: "客户预算收缩",
    category: "income_down",
    description: "合作客户预算收缩，你的收入下降 20%，持续时间还不确定。",
    effect: {
      type: "add_uncertain_active_effect",
      target: "income_percent",
      amount: -0.2,
      minMonths: 2,
      recoveryChance: 0.3,
      maxMonths: 8,
      recoveryText: "客户预算恢复，你的收入回到原来的水平。",
    },
    insight: "收入下降，持续时间不确定。",
  },
  {
    id: "year_end_bonus",
    title: "年终奖到账",
    category: "choice",
    description: "年终奖到账，金额约等于 1 个月收入。",
    choices: [
      {
        label: "补进现金储备",
        resultText: "你把年终奖留作现金储备。",
        effect: { type: "change_savings_by_income_percent", amount: 1 },
      },
      {
        label: "加码定投或先存着",
        resultText: "如果已有定投计划，就拿一部分奖金加码；如果还没开始定投，就先放进现金储备。",
        effect: { type: "bonus_invest_or_reserve", investPercent: 0.5 },
      },
      {
        label: "安排一次家庭犒劳",
        resultText: "你订了一家一直想去的餐厅，再安排一个近郊周末，剩下的钱补进储备。",
        effect: { type: "change_savings_by_income_percent", amount: 0.65 },
      },
    ],
    insight: "年终奖已经入账。",
  },
  {
    id: "side_income",
    title: "副业收入",
    category: "choice",
    description: "这个月有一笔副业机会。",
    choices: [
      {
        label: "接下这单",
        resultText: "你接下这单，收入变多，但这个月也多了交通、工具、外包杂费和额外工作时间。",
        wellbeingCost: 4,
        wellbeingReason: "副业占用了较多休息时间",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.22 },
            { type: "one_month_expense_change", amount: 1200 },
          ],
        },
      },
      {
        label: "只接小单",
        resultText: "你只接一部分，收入增加一点，节奏也比较可控。",
        wellbeingCost: 1,
        wellbeingReason: "小单占用了一部分休息时间",
        effect: { type: "one_month_income_percent", amount: 0.1 },
      },
      {
        label: "这次不接",
        resultText: "你保留休息时间，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "副业机会已经处理。",
  },
  {
    id: "spending_control",
    title: "控制消费成功",
    category: "positive",
    description: "你主动控制消费，本月支出减少约 12%。",
    effect: { type: "one_month_expense_percent", amount: -0.12 },
    insight: "本月支出减少约 12%。",
  },
  {
    id: "tax_refund",
    title: "退税或补贴到账",
    category: "choice",
    description: "退税或补贴到账 8000 元。",
    choices: [
      {
        label: "补进现金储备",
        resultText: "你把这笔钱留作现金储备。",
        effect: { type: "change_savings", amount: 8000 },
      },
      {
        label: "加码定投或先存着",
        resultText: "如果已有定投计划，就拿一半补贴加码；如果还没开始定投，就先放进现金储备。",
        effect: { type: "invest_or_reserve", amount: 8000, investPercent: 0.5 },
      },
      {
        label: "换一件耐用品",
        resultText: "你换了家里用很久的床垫，睡眠舒服一些，剩余部分进入储备。",
        effect: { type: "change_savings", amount: 3200 },
      },
    ],
    insight: "这笔到账已经处理。",
  },
  {
    id: "freelance_referral",
    title: "朋友介绍兼职单",
    category: "choice",
    description: "朋友介绍了一笔兼职单。",
    choices: [
      {
        label: "接完整单",
        resultText: "你接下完整兼职，本月收入增加不少，但也多了沟通、交通、交付成本和额外工作时间。",
        wellbeingCost: 4,
        wellbeingReason: "完整兼职明显压缩了休息时间",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.26 },
            { type: "one_month_expense_change", amount: 1800 },
          ],
        },
      },
      {
        label: "只接一部分",
        resultText: "你只接最确定的一部分，本月收入增加，但压力小一些。",
        wellbeingCost: 1,
        wellbeingReason: "兼职占用了一部分休息时间",
        effect: { type: "one_month_income_percent", amount: 0.12 },
      },
      {
        label: "婉拒这次",
        resultText: "你没有接这笔兼职，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "兼职机会已经处理。",
  },
  {
    id: "sell_unused",
    title: "闲置物品卖出",
    category: "positive",
    description: "清理出一批闲置物品，可以打包立即卖出，也可以分别挂售。",
    choices: [
      {
        label: "打包立即卖出",
        resultText: "现在就完成交易。",
        effect: { type: "change_savings", amount: 1200 },
      },
      {
        label: "分别挂售",
        resultText: "两个月后可能收入更多。",
        hideImpact: true,
        effect: {
          type: "schedule_random_savings_effect",
          id: "sell_unused_follow_up",
          triggerDelay: 2,
          preserveDelay: true,
          title: "闲置物品挂售结果",
          outcomes: [
            {
              id: "sold_most",
              weight: 0.6,
              amount: 1800,
              message: "分别挂售的闲置物品大多卖出去了。",
            },
            {
              id: "sold_half",
              weight: 0.4,
              amount: 600,
              message: "两个月后，闲置物品只卖出去一半。",
            },
          ],
        },
      },
    ],
    insight: "闲置物品已经处理。",
  },
  {
    id: "subscription_cleanup",
    title: "取消闲置订阅",
    category: "positive",
    description: "你清理了几个很少使用的订阅，常规月支出减少 600 元。",
    effect: { type: "add_active_effect", target: "expense", amount: -600, duration: 999 },
    insight: "订阅支出已经减少。",
  },
  {
    id: "deposit_return",
    title: "旧押金退回",
    category: "positive",
    description: "之前的一笔押金退回，现金储备增加 3000 元。",
    effect: { type: "change_savings", amount: 3000 },
    insight: "旧押金已经到账。",
  },
  {
    id: "shopping_card",
    title: "公司发放购物卡",
    category: "positive",
    description: "公司发放购物卡，本月日常支出减少 1000 元。",
    effect: { type: "one_month_expense_change", amount: -1000 },
    insight: "本月部分日常支出被抵扣。",
  },
  {
    id: "credit_card_points",
    title: "积分抵扣账单",
    category: "positive",
    description: "你用信用卡积分抵扣账单，本月支出减少 500 元。",
    effect: { type: "one_month_expense_change", amount: -500 },
    insight: "本月账单已经抵扣一部分。",
  },
  {
    id: "athlete_commercial_appearance",
    title: "商务活动出席",
    category: "positive",
    eventLabel: "职业机会",
    eventMark: "CAREER",
    weight: 0.9,
    description: "赛事合作方邀请你参加一场线下商务活动。",
    choices: [
      {
        label: "确认出席",
        resultText: "本月收入增加约 20%，交通和造型支出增加 800 元，也占用了一部分训练时间。",
        wellbeingCost: 1,
        wellbeingReason: "商务活动占用了一部分训练和休息时间",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.2 },
            { type: "one_month_expense_change", amount: 800 },
          ],
        },
      },
      {
        label: "保留训练安排",
        resultText: "你没有参加这次活动，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "商务活动邀请已经处理。",
  },
  {
    id: "athlete_brand_endorsement",
    title: "品牌代言邀约",
    category: "positive",
    eventLabel: "职业机会",
    eventMark: "CAREER",
    weight: 0.45,
    description: "一个运动品牌邀请你拍摄推广内容并参加新品发布活动。",
    choices: [
      {
        label: "接受完整合作",
        resultText: "本月收入增加约 45%，拍摄、交通和团队支出增加 2,500 元，行程也明显变满。",
        wellbeingCost: 2,
        wellbeingReason: "完整代言合作压缩了训练和休息安排",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.45 },
            { type: "one_month_expense_change", amount: 2500 },
          ],
        },
      },
      {
        label: "只参加发布活动",
        resultText: "本月收入增加约 18%，交通和造型支出增加 600 元，额外占用半天时间。",
        wellbeingCost: 1,
        wellbeingReason: "发布活动占用了少量训练时间",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.18 },
            { type: "one_month_expense_change", amount: 600 },
          ],
        },
      },
      {
        label: "这次不合作",
        resultText: "你没有接下这次合作，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "品牌邀约已经处理。",
  },
  {
    id: "minor_illness",
    title: "自己生病休养",
    category: "health_risk",
    description: "你因为身体原因休养，本月收入减少 30%，同时医疗支出增加 5000 元。",
    effect: {
      type: "compound",
      effects: [
        { type: "one_month_income_percent", amount: -0.3 },
        { type: "change_savings", amount: -5000 },
      ],
    },
    insight: "本月收入和储备同时受到影响。",
  },
  {
    id: "family_care",
    title: "照顾家人",
    category: "health_risk",
    description: "你需要请假照顾家人，本月收入减少约 25%。",
    effect: { type: "one_month_income_percent", amount: -0.25 },
    insight: "本月收入减少。",
  },
  {
    id: "dental_cost",
    title: "牙齿治疗",
    category: "health_risk",
    description: "牙齿治疗方案确定，总费用可以一次支付，也可以按月分期。",
    choices: [
      {
        label: "一次性支付 20,000 元",
        resultText: "本次治疗费用一次结清。",
        effect: { type: "change_savings", amount: -20000 },
      },
      {
        label: "分 12 次支付",
        resultText: "每次支付 2,500 元，共支付 12 次。",
        effect: { type: "add_active_effect", target: "expense", amount: 2500, duration: 12 },
      },
    ],
    insight: "牙齿治疗付款方式已经确定。",
  },
  {
    id: "insurance_gap",
    title: "医保报销后的自付账单",
    category: "health_risk",
    description: "一次治疗后，医保已经报销了一部分，但仍有 15000 元需要自己支付。",
    effect: { type: "change_savings", amount: -15000 },
    insight: "自付部分从现金储备里支出。",
  },
  {
    id: "child_fever",
    title: "孩子反复发烧",
    category: "health_risk",
    description: "孩子反复发烧，你本月请假照顾并支出检查费用，收入减少约 15%，现金储备减少 2500 元。",
    effect: {
      type: "compound",
      effects: [
        { type: "one_month_income_percent", amount: -0.15 },
        { type: "change_savings", amount: -2500 },
      ],
    },
    insight: "本月收入和储备同时受到影响。",
  },
  {
    id: "sports_injury",
    title: "运动受伤",
    category: "health_risk",
    description: "运动受伤后需要检查和康复，一次性支出 6500 元。",
    effect: { type: "change_savings", amount: -6500 },
    insight: "运动康复支出已经结清。",
  },
  {
    id: "insurance_review_choice",
    title: "检查保障配置",
    category: "choice",
    description: "你准备检查自己的保障配置。可以花一点钱补齐基础保障，也可以先不调整。",
    choices: [
      {
        label: "补齐基础保障",
        resultText: "你每月增加 900 元保障支出。后续遇到部分健康风险时，可减少一次性储备损失。",
        effect: { type: "start_protection_plan", monthlyAmount: 900, duration: 12, coverageRate: 0.5, maxReduction: 20000 },
      },
      {
        label: "先不调整",
        resultText: "你暂时保留现金储备，不新增固定支出。",
        effect: { type: "none" },
      },
    ],
    insight: "保障选择已经记录。",
  },
  {
    id: "rent_or_commute_choice",
    title: "离公司近一点",
    category: "choice",
    description: "你在考虑换到离公司更近的住处。通勤会轻松，但房租会上升。",
    choices: [
      {
        label: "搬近一点",
        resultText: "你选择缩短通勤，常规月支出增加 1800 元；三个月后精力恢复，常规月收入增加 1200 元。",
        effect: {
          type: "compound",
          effects: [
            { type: "add_active_effect", target: "expense", amount: 1800, duration: 999 },
            {
              type: "schedule_active_effect",
              id: "rent_commute_income_boost",
              triggerDelay: 3,
              target: "income",
              amount: 1200,
              duration: 999,
              title: "搬近后的精力恢复",
              message: "住得离公司近一点后，你把通勤时间换回了精力，开始承接更好的工作机会。",
            },
          ],
        },
      },
      {
        label: "暂时不搬",
        resultText: "你继续承受较长通勤，短期省下房租，但精力被通勤消耗，常规月收入减少 1000 元。",
        wellbeingCost: 4,
        wellbeingReason: "较长通勤持续消耗精力",
        effect: { type: "add_active_effect", target: "income", amount: -1000, duration: 999 },
      },
    ],
    insight: "通勤选择已经生效。",
  },
  {
    id: "family_trip_choice",
    title: "带家人短途旅行",
    category: "choice",
    description: "你想带家人出去放松两天。可以现在就去，也可以暂时推迟。",
    choices: [
      {
        label: "安排旅行",
        resultText: "你花 5800 元安排了一次短途旅行，现金储备减少，但家庭压力得到释放。",
        effect: { type: "change_savings", amount: -5800 },
      },
      {
        label: "暂时推迟",
        resultText: "你保留大部分现金储备，但会在后面安排一次补偿活动。",
        wellbeingCost: 2,
        wellbeingReason: "推迟了原本期待的家庭旅行",
        effect: {
          type: "schedule_savings_effect",
          id: "family_trip_makeup",
          triggerDelay: 2,
          amount: -1200,
          title: "补偿一次周末安排",
          message: "之前推迟的短途旅行，后来换成了一次周末安排。",
        },
      },
    ],
    insight: "旅行选择已经生效。",
  },
  {
    id: "kids_theme_park",
    title: "带孩子去游乐场",
    category: "one_time_cost",
    description: "周末带孩子去游乐场，门票、交通和餐饮一次性支出 1200 元。",
    effect: { type: "change_savings", amount: -1200 },
    insight: "游乐场支出已经结清。",
  },
  {
    id: "movie_weekend",
    title: "周末看电影聚餐",
    category: "one_time_cost",
    description: "你和家人朋友看电影、简单聚餐，一次性支出 600 元。",
    effect: { type: "change_savings", amount: -600 },
    insight: "周末娱乐支出已经结清。",
  },
  {
    id: "hobby_class",
    title: "报名兴趣课程",
    category: "choice",
    group: "interest",
    description: "你想报名一个兴趣课程，让生活不只是工作和账单。课程费用 1800 元。",
    choices: [
      {
        label: "报名",
        resultText: "你支付 1800 元报名课程，现金储备减少。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -1800 },
            {
              type: "schedule_savings_effect",
              id: "hobby_small_order",
              triggerDelay: 4,
              amount: 800,
              title: "兴趣带来小单",
              message: "兴趣课程里认识的朋友介绍了一笔小单。",
            },
          ],
        },
      },
      {
        label: "先等等",
        resultText: "你先不报名，也暂时放下了这次兴趣安排。",
        wellbeingCost: 1,
        wellbeingReason: "暂时放下了想参加的兴趣安排",
        effect: { type: "none" },
      },
    ],
    insight: "兴趣课程选择已经记录。",
  },
  {
    id: "fishing_gear_choice",
    title: "入门钓鱼装备",
    category: "choice",
    group: "interest",
    description: "朋友约你周末去钓鱼。想认真玩的话，需要买一套入门装备。",
    choices: [
      {
        label: "买一套装备",
        resultText: "你花 1200 元买了基础装备，现金储备减少。",
        effect: { type: "change_savings", amount: -1200 },
      },
      {
        label: "先借朋友的",
        resultText: "你先借装备体验一次，只承担交通和餐食。",
        effect: { type: "change_savings", amount: -300 },
      },
    ],
    insight: "钓鱼装备选择已经记录。",
  },
  {
    id: "outdoor_hike_choice",
    title: "周末户外徒步",
    category: "choice",
    group: "interest",
    description: "你想参加一次周末户外徒步，报名、装备补充和交通都要花钱。",
    choices: [
      {
        label: "参加徒步",
        resultText: "你支付 1500 元参加徒步，现金储备减少。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -1500 },
            {
              type: "schedule_savings_effect",
              id: "hike_gear_topup",
              triggerDelay: 2,
              amount: -600,
              title: "补充户外装备",
              message: "徒步之后，你补了几件基础户外装备。",
            },
          ],
        },
      },
      {
        label: "城市公园走走",
        resultText: "你选择低成本放松，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "户外安排已经记录。",
  },
  {
    id: "yoga_membership_choice",
    title: "瑜伽体验课",
    category: "choice",
    group: "interest",
    description: "你试了一节瑜伽课，想买一个 3 个月的小课包。",
    choices: [
      {
        label: "买小课包",
        resultText: "你每月增加 1200 元运动支出，持续 3 个月。",
        effect: {
          type: "compound",
          effects: [
            { type: "add_active_effect", target: "expense", amount: 1200, duration: 3 },
            {
              type: "schedule_savings_effect",
              id: "yoga_small_purchase",
              triggerDelay: 2,
              amount: -500,
              title: "瑜伽用品补充",
              message: "你补充了一些瑜伽用品。",
            },
          ],
        },
      },
      {
        label: "先跟练视频",
        resultText: "你暂时不买课包，现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "瑜伽课程选择已经记录。",
  },
  {
    id: "career_course",
    title: "职业提升课程",
    category: "choice",
    description: "你看到一个职业提升课程，费用 8000 元，可能帮助你未来提升收入。是否报名？",
    choices: [
      {
        label: "报名",
        resultText: "你支付 8000 元报名课程，未来可能获得收入提升机会。",
        effect: { type: "career_course_plan", cost: 8000 },
      },
      {
        label: "暂不报名",
        resultText: "你选择保留现金储备，暂不报名。",
        effect: { type: "none" },
      },
    ],
    insight: "课程选择已经记录。",
  },
  {
    id: "buy_car_choice",
    title: "是否换车",
    category: "choice",
    description: "现在换车可以改善通勤，但会减少储备并增加月供。是否换车？",
    choices: [
      {
        label: "换车",
        resultText: "你换了一辆车，现金储备减少 50000 元，每月支出增加 2500 元。",
        effect: { type: "buy_car" },
      },
      {
        label: "暂不换车",
        resultText: "你选择暂不换车，保留现金储备，但旧车后面可能需要小修。",
        effect: {
          type: "schedule_savings_effect",
          id: "old_car_minor_repair",
          triggerDelay: 4,
          amount: -1800,
          title: "旧车小修",
          message: "暂时没换车后，旧车做了一次小修。",
        },
      },
    ],
    insight: "换车选择已经记录。",
  },
  {
    id: "emergency_fund_choice",
    title: "建立应急储备计划",
    category: "choice",
    description: "你决定是否从这个月开始，压缩一部分可选消费支出作为应急储备。",
    choices: [
      {
        label: "开始储备",
        resultText: "你开始压缩可选消费支出，常规月支出减少约 15%，持续 6 个月。",
        wellbeingCost: 4,
        wellbeingReason: "连续六个月压缩可选消费",
        effect: { type: "add_active_effect", target: "expense_percent", amount: -0.15, duration: 6 },
      },
      {
        label: "暂不调整",
        resultText: "你暂时保持原有消费习惯。",
        effect: { type: "none" },
      },
    ],
    insight: "储备计划选择已经记录。",
  },
  {
    id: "career_white_collar_project",
    title: "跨部门项目邀请",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["young_worker"],
    description: "另一个部门邀请你参与一个三个月的重点项目，需要在原有工作之外承担一部分协调任务。",
    choices: [
      {
        label: "接下项目",
        resultText: "本月增加 800 元协作支出，也占用了一部分休息时间；三个月后获得为期六个月的项目津贴。",
        wellbeingCost: 3,
        wellbeingReason: "跨部门项目增加了额外协调工作",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_expense_change", amount: 800 },
            {
              type: "schedule_active_effect",
              id: "white_collar_project_income",
              triggerDelay: 3,
              preserveDelay: true,
              target: "income_percent",
              amount: 0.08,
              duration: 6,
              title: "跨部门项目进入新阶段",
              message: "跨部门项目进入新阶段，你开始领取项目津贴。",
            },
          ],
        },
      },
      {
        label: "保持原工作节奏",
        resultText: "你没有接下额外项目，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "跨部门项目已经安排。",
  },
  {
    id: "career_creator_brand_deal",
    title: "平台商务合作",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["freelancer"],
    description: "平台转来一笔品牌合作，需要决定这次承接多少内容。",
    choices: [
      {
        label: "接完整合作",
        resultText: "本月收入增加约 28%，拍摄、道具和外包支出增加 3,200 元，交付周期也排得很满。",
        wellbeingCost: 4,
        wellbeingReason: "完整商务合作明显压缩了休息时间",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.28 },
            { type: "one_month_expense_change", amount: 3200 },
          ],
        },
      },
      {
        label: "只接轻量合作",
        resultText: "本月收入增加约 14%，制作支出增加 800 元，工作量有所增加。",
        wellbeingCost: 1,
        wellbeingReason: "轻量合作占用了一部分个人时间",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.14 },
            { type: "one_month_expense_change", amount: 800 },
          ],
        },
      },
      {
        label: "这次不接",
        resultText: "你没有接下这次合作，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "平台合作已经处理。",
  },
  {
    id: "career_restaurant_equipment",
    title: "后厨设备升级",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["small_shop_owner"],
    description: "后厨的一台核心设备效率下降，可以直接换新，也可以先维修继续使用。",
    choices: [
      {
        label: "一次更换新设备",
        resultText: "一次性支付 18,000 元，之后常规月支出减少 1,200 元。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -18000 },
            { type: "add_active_effect", target: "expense", amount: -1200, duration: 999 },
          ],
        },
      },
      {
        label: "继续维修使用",
        resultText: "支付 4,000 元维修设备，暂时保留更多现金。",
        effect: { type: "change_savings", amount: -4000 },
      },
    ],
    insight: "后厨设备已经处理。",
  },
  {
    id: "career_cafe_footfall",
    title: "商圈客流变少",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["cafe_owner"],
    description: "附近道路施工，工作日到店客流明显减少，预计会持续四个月。",
    choices: [
      {
        label: "保持全天营业",
        resultText: "继续保持原来的营业时间，常规月收入减少约 12%，持续 4 个月。",
        effect: { type: "add_active_effect", target: "income_percent", amount: -0.12, duration: 4 },
      },
      {
        label: "缩短下午营业",
        resultText: "缩短客流较少时段的营业时间，常规月收入减少约 18%，月支出减少约 6%，持续 4 个月。",
        effect: {
          type: "compound",
          effects: [
            { type: "add_active_effect", target: "income_percent", amount: -0.18, duration: 4 },
            { type: "add_active_effect", target: "expense_percent", amount: -0.06, duration: 4 },
          ],
        },
      },
    ],
    insight: "这段时间的营业安排已经确定。",
  },
  {
    id: "cafe_blogger_promotion",
    title: "邀请探店博主",
    category: "choice",
    description: "一位本地探店博主愿意来店里拍摄一期内容。",
    choices: [
      {
        label: "付费邀请到店",
        resultText: "支付 3,000 元合作费用，下个月开始常规月收入增加约 15%，持续 3 个月。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -3000 },
            {
              type: "schedule_active_effect",
              id: "cafe_blogger_income",
              triggerDelay: 1,
              preserveDelay: true,
              target: "income_percent",
              amount: 0.15,
              duration: 3,
              title: "探店内容带来新客",
              message: "探店内容发布后，店里的到店客流增加了。",
            },
          ],
        },
      },
      {
        label: "自己拍短视频",
        resultText: "本月增加 500 元拍摄支出，下个月开始常规月收入增加约 6%，持续 3 个月。",
        wellbeingCost: 2,
        wellbeingReason: "自己拍摄和运营账号占用了休息时间",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_expense_change", amount: 500 },
            {
              type: "schedule_active_effect",
              id: "cafe_self_promotion_income",
              triggerDelay: 1,
              preserveDelay: true,
              target: "income_percent",
              amount: 0.06,
              duration: 3,
              title: "短视频带来一些新客",
              message: "你自己拍摄的短视频陆续带来了一些新客。",
            },
          ],
        },
      },
      {
        label: "暂时不宣传",
        resultText: "这次不安排额外宣传，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "这次宣传安排已经确定。",
  },
  {
    id: "cafe_stray_cat",
    title: "门口来了一只流浪猫",
    category: "choice",
    description: "一只流浪猫最近总在店门口休息，看起来已经慢慢熟悉了这里。",
    choices: [
      {
        label: "检查后留在店里",
        resultText: "支付 1,200 元完成检查、驱虫和基础用品，猫留在了店里。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -1200 },
            {
              type: "schedule_random_savings_effect",
              id: "cafe_cat_follow_up",
              triggerDelay: 3,
              preserveDelay: true,
              title: "店里的猫有了新变化",
              outcomes: [
                {
                  id: "cafe_cat_mascot",
                  weight: 0.5,
                  amount: 0,
                  title: "小店成了附近的猫咖",
                  message: "常来店里的客人开始专程来看猫，小店的热度明显上升。",
                  activeEffect: {
                    name: "猫咖热度",
                    target: "income_percent",
                    amount: 0.2,
                    duration: 4,
                  },
                },
                {
                  id: "cafe_cat_kittens",
                  weight: 0.5,
                  amount: 0,
                  title: "店里多了几只小猫",
                  message: "猫生下了几只小猫，接下来需要增加猫粮、猫砂和护理用品。",
                  activeEffect: {
                    name: "幼猫照料",
                    target: "expense",
                    amount: 1200,
                    duration: 6,
                  },
                },
              ],
            },
          ],
        },
      },
      {
        label: "联系附近救助站",
        resultText: "支付 300 元检查和交通费用，把猫送到了附近的救助站。",
        effect: { type: "change_savings", amount: -300 },
      },
    ],
    insight: "这只猫已经得到安置。",
  },
  {
    id: "career_teacher_public_course",
    title: "成人钢琴小班",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["stable_employee"],
    description: "琴行准备开设周末成人钢琴小班，邀请你负责课程设计和授课。",
    choices: [
      {
        label: "接下周末小班",
        resultText: "本月收入增加约 16%，曲谱和课程资料支出增加 600 元，也占用了两个周末。",
        wellbeingCost: 2,
          wellbeingReason: "小班课程准备占用了两个周末",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.16 },
            { type: "one_month_expense_change", amount: 600 },
          ],
        },
      },
      {
        label: "保持一对一教学",
        resultText: "你维持原来的教学安排，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "周末课程已经安排。",
  },
  {
    id: "career_sales_major_client",
    title: "大客户订单",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["single_parent"],
    description: "一个大客户准备集中下单，但交付、差旅和售后工作也会明显增加。",
    choices: [
      {
        label: "接下完整订单",
        resultText: "本月收入增加约 32%，差旅和执行支出增加 3,500 元，工作安排非常紧。",
        wellbeingCost: 4,
        wellbeingReason: "完整订单带来了高强度执行压力",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.32 },
            { type: "one_month_expense_change", amount: 3500 },
          ],
        },
      },
      {
        label: "只接部分订单",
        resultText: "本月收入增加约 16%，执行支出增加 900 元，工作量有所增加。",
        wellbeingCost: 1,
        wellbeingReason: "部分订单增加了一部分工作负担",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.16 },
            { type: "one_month_expense_change", amount: 900 },
          ],
        },
      },
    ],
    insight: "大客户订单已经安排。",
  },
  {
    id: "career_senior_engineer_upgrade",
    title: "核心系统升级",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["senior_engineer"],
    description: "核心系统进入升级窗口，团队问你要不要负责这次改造。",
    choices: [
      {
        label: "负责这次改造",
        resultText: "本月获得项目奖金，同时增加交通、工作餐支出和一段高强度加班。",
        wellbeingCost: 3,
        wellbeingReason: "负责系统改造带来高强度加班",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.2 },
            { type: "one_month_expense_change", amount: 2500 },
          ],
        },
      },
      {
        label: "只做技术支持",
        resultText: "本月获得一笔技术支持补贴。",
        effect: { type: "one_month_income_percent", amount: 0.08 },
      },
    ],
    insight: "系统升级工作已经安排。",
  },
  {
    id: "career_data_analyst_model",
    title: "临时数据项目",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["data_analyst"],
    description: "业务部门临时增加一个数据项目，需要决定这次怎么交付。",
    choices: [
      {
        label: "购买分析工具",
        resultText: "支付 3,000 元工具费，两个月后开始承接更高价项目。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -3000 },
            {
              type: "schedule_active_effect",
              id: "data_tool_income",
              triggerDelay: 2,
              preserveDelay: true,
              target: "income",
              amount: 1500,
              duration: 6,
              title: "数据工具开始回本",
              message: "之前购买的分析工具开始用于新的项目。",
            },
          ],
        },
      },
      {
        label: "沿用现有工具",
        resultText: "按现有方式完成，本月获得项目补贴。",
        effect: { type: "one_month_income_percent", amount: 0.08 },
      },
    ],
    insight: "临时数据项目已经处理。",
  },
  {
    id: "career_architect_bid",
    title: "方案竞标",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["architect"],
    description: "一个新项目公开竞标，模型、效果图和打印费用需要自己先垫付。",
    choices: [
      {
        label: "独立完成竞标",
        resultText: "先投入 6,000 元，并独自承担方案制作，三个月后公布结果。",
        wellbeingCost: 4,
        wellbeingReason: "独立竞标占用了大量个人时间",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -6000 },
            {
              type: "schedule_random_savings_effect",
              id: "architect_bid_result",
              triggerDelay: 3,
              preserveDelay: true,
              title: "竞标结果公布",
              outcomes: [
                { id: "won", weight: 0.4, amount: 22000, message: "你独立完成的方案中标，项目首款到账。" },
                { id: "lost", weight: 0.6, amount: 0, message: "这次方案没有中标。" },
              ],
            },
          ],
        },
      },
      {
        label: "和同行联合竞标",
        resultText: "先投入 2,500 元，三个月后结算合作费用。",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -2500 },
            {
              type: "schedule_savings_effect",
              id: "architect_joint_bid_result",
              triggerDelay: 3,
              preserveDelay: true,
              amount: 7000,
              title: "联合竞标结算",
              message: "联合竞标项目完成了第一阶段结算。",
            },
          ],
        },
      },
    ],
    insight: "竞标方式已经确定。",
  },
  {
    id: "career_doctor_training",
    title: "进修名额",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["doctor"],
    description: "科室有一个外院进修名额，也可以继续留院增加门诊排班。",
    choices: [
      {
        label: "自费参加进修",
        resultText: "支付 12,000 元，并投入一段额外学习时间；三个月后常规月收入增加 2,000 元。",
        wellbeingCost: 2,
        wellbeingReason: "进修占用了一部分休息时间",
        effect: {
          type: "compound",
          effects: [
            { type: "change_savings", amount: -12000 },
            {
              type: "schedule_active_effect",
              id: "doctor_training_income",
              triggerDelay: 3,
              preserveDelay: true,
              target: "income",
              amount: 2000,
              duration: 12,
              title: "进修后的新排班",
              message: "进修结束后，你开始承担新的门诊安排。",
            },
          ],
        },
      },
      {
        label: "留院增加门诊",
        resultText: "本月增加门诊排班，收入提高约 15%，休息时间相应减少。",
        wellbeingCost: 3,
        wellbeingReason: "增加门诊排班压缩了休息时间",
        effect: { type: "one_month_income_percent", amount: 0.15 },
      },
    ],
    insight: "这次工作安排已经确定。",
  },
  {
    id: "career_athlete_equipment",
    title: "赛季装备更新",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["athlete"],
    description: "新赛季开始前，常用训练装备已经出现明显磨损。",
    choices: [
      {
        label: "更换专业装备",
        resultText: "一次性支付 6,000 元。",
        effect: { type: "change_savings", amount: -6000 },
      },
      {
        label: "先继续使用",
        resultText: "暂时继续使用这套已经明显磨损的装备。",
        wellbeingCost: 2,
        wellbeingReason: "继续使用磨损装备增加了训练负担",
        effect: {
          type: "schedule_random_savings_effect",
          id: "athlete_old_equipment_follow_up",
          triggerDelay: 3,
          preserveDelay: true,
          title: "旧装备使用结果",
          outcomes: [
            {
              id: "training_accident",
              weight: 0.45,
              title: "训练意外",
              incomeLossPercent: 0.25,
              savingsCost: 5000,
              message: "旧装备在训练中失效，你暂停了一部分训练和比赛，并支付了检查、理疗与更换装备的费用。",
            },
            {
              id: "equipment_held_up",
              weight: 0.55,
              amount: 0,
              silent: true,
              title: "旧装备暂时撑住了",
              message: "这段时间没有发生意外，现金流没有变化。",
            },
          ],
        },
      },
    ],
    insight: "赛季装备已经处理。",
  },
  {
    id: "career_programmer_on_call",
    title: "线上故障值班",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["programmer"],
    description: "产品上线进入值班期，可以独立接下值班，也可以和同事轮值。",
    choices: [
      {
        label: "独立接下值班",
        resultText: "本月收入增加约 18%，交通和工作餐支出增加 2,400 元，夜间休息也被频繁打断。",
        wellbeingCost: 4,
        wellbeingReason: "独立值班频繁打断夜间休息",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.18 },
            { type: "one_month_expense_change", amount: 2400 },
          ],
        },
      },
      {
        label: "和同事轮值",
        resultText: "本月收入增加约 9%，额外支出增加 600 元，也占用少量夜间休息。",
        wellbeingCost: 1,
        wellbeingReason: "轮值占用了少量夜间休息",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.09 },
            { type: "one_month_expense_change", amount: 600 },
          ],
        },
      },
    ],
    insight: "线上值班已经安排。",
  },
  {
    id: "career_home_organizer_order",
    title: "全屋收纳加单",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["home_organizer"],
    description: "客户临时把局部整理升级为全屋收纳，需要重新安排人手和物料。",
    choices: [
      {
        label: "自己完成全部项目",
        resultText: "本月收入增加约 25%，物料和交通支出增加 2,500 元，连续几天都排得很满。",
        wellbeingCost: 4,
        wellbeingReason: "独自完成全屋项目造成明显透支",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.25 },
            { type: "one_month_expense_change", amount: 2500 },
          ],
        },
      },
      {
        label: "找助手一起完成",
        resultText: "本月收入增加约 18%，助手和物料支出增加 1,000 元，工作量仍有所增加。",
        wellbeingCost: 1,
        wellbeingReason: "加单增加了一部分工作负担",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.18 },
            { type: "one_month_expense_change", amount: 1000 },
          ],
        },
      },
      {
        label: "只做核心区域",
        resultText: "本月收入增加约 10%，没有额外支出。",
        effect: { type: "one_month_income_percent", amount: 0.1 },
      },
    ],
    insight: "这笔加单已经安排。",
  },
  {
    id: "career_librarian_weekend_event",
    title: "周末阅读活动",
    category: "choice",
    eventLabel: "职业事件",
    eventMark: "CAREER",
    careerIdentityIds: ["librarian"],
    description: "图书馆计划增加一场周末阅读活动，需要确定活动形式。",
    choices: [
      {
        label: "自己主持活动",
        resultText: "本月收入增加约 12%，准备资料支出增加 500 元，也占用了一个完整周末。",
        wellbeingCost: 2,
        wellbeingReason: "主持活动占用了完整周末",
        effect: {
          type: "compound",
          effects: [
            { type: "one_month_income_percent", amount: 0.12 },
            { type: "one_month_expense_change", amount: 500 },
          ],
        },
      },
      {
        label: "协调外部讲者",
        resultText: "本月收入增加约 6%，没有额外支出。",
        effect: { type: "one_month_income_percent", amount: 0.06 },
      },
    ],
    insight: "周末活动已经安排。",
  },
];

if (typeof module !== "undefined" && module.exports) module.exports = eventCards;
