// 事件卡牌配置
//
// 这个文件只放卡牌数据，方便非工程同事调整文案、金额、持续时间和选项。
// 主游戏逻辑在 script.js；新增 effect 类型前，请先确认 script.js 里有对应处理逻辑。

var eventCards = [
  {
    id: "kids_classes",
    title: "孩子报课外班",
    category: "expense_up",
    description: "孩子新增课外班，每月支出增加 2000 元，持续 6 个月。",
    effect: { type: "add_active_effect", target: "expense", amount: 2000, duration: 6 },
    insight: "这类支出最容易悄悄变成新常态。它不吓人，但会每个月来敲一次门。",
  },
  {
    id: "rent_up",
    title: "房租上涨",
    category: "expense_up",
    description: "房租续约上涨，常规月支出增加约 8%，持续 12 个月。",
    effect: { type: "add_active_effect", target: "expense_percent", amount: 0.08, duration: 12 },
    insight: "房租不是一次痛，是每个月的小小重力。安全垫厚不厚，很快会有感觉。",
  },
  {
    id: "parents_support",
    title: "父母生活支持增加",
    category: "expense_up",
    description: "家里老人需要更多生活支持，常规月支出增加约 8%，持续 6 个月。",
    effect: { type: "add_active_effect", target: "expense_percent", amount: 0.08, duration: 6 },
    insight: "家庭责任不是坏事，只是它会把“我的钱”变成“我们家的调度题”。",
  },
  {
    id: "childcare_cost",
    title: "育儿支出增加",
    category: "expense_up",
    description: "家庭育儿支出增加，常规月支出增加约 10%，持续 12 个月。",
    effect: { type: "add_active_effect", target: "expense_percent", amount: 0.1, duration: 12 },
    insight: "育儿支出很少只出现一次。它更像地图上的连续地形，走进去以后要多算几步。",
  },
  {
    id: "elder_hospital",
    title: "老人住院",
    category: "one_time_cost",
    description: "家里老人突发住院，自付医疗支出 50000 元。",
    effect: { type: "change_savings", amount: -50000 },
    insight: "这一下不是普通扣血，是直接打到储备条。幸好地图还没结束。",
  },
  {
    id: "car_repair",
    title: "车辆维修",
    category: "one_time_cost",
    description: "车子出现故障，需要更换零件和保养，一次性支出 4500 元。",
    effect: { type: "change_savings", amount: -4500 },
    insight: "车不会挑你手头宽裕的时候坏。现金储备有时候就是给这种时刻留的。",
  },
  {
    id: "moving_cost",
    title: "搬家支出",
    category: "one_time_cost",
    description: "因为工作或家庭原因搬家，搬运和杂费合计 5000 元。",
    effect: { type: "change_savings", amount: -5000 },
    insight: "搬家像换地图，但押金和杂费会先来收门票。",
  },
  {
    id: "home_appliance",
    title: "家电集中更换",
    category: "one_time_cost",
    description: "家里几件大件家电集中更换，一次性支出 10000 元。",
    effect: { type: "change_savings", amount: -10000 },
    insight: "家电一起罢工的时候，预算表通常会沉默三秒。",
  },
  {
    id: "property_fee_up",
    title: "夏季电费上涨",
    category: "expense_up",
    description: "夏天常开空调，电费明显变高，每月支出增加 500 元，持续 3 个月。",
    effect: { type: "add_active_effect", target: "expense", amount: 500, duration: 3 },
    insight: "季节性支出不大，但会在某几个月集中冒出来。现金流要留一点呼吸空间。",
  },
  {
    id: "commute_cost_up",
    title: "通勤成本增加",
    category: "expense_up",
    description: "工作地点调整后，通勤距离变远，常规月支出增加 400 元。",
    effect: { type: "add_active_effect", target: "expense", amount: 400, duration: 999 },
    insight: "通勤变远不是一次性事件，它会每天从时间和现金流里扣一点。",
  },
  {
    id: "nanny_help",
    title: "临时请人照护",
    category: "expense_up",
    description: "家里需要临时请人帮忙照护，常规月支出增加约 10%，持续 4 个月。",
    effect: { type: "add_active_effect", target: "expense_percent", amount: 0.1, duration: 4 },
    insight: "有些支出买的是喘息时间，但现金流会先感受到重量。",
  },
  {
    id: "phone_replacement",
    title: "手机突然报废",
    category: "one_time_cost",
    description: "手机突然报废，工作和生活都离不开，只能立刻更换，一次性支出 5000 元。",
    effect: { type: "change_savings", amount: -5000 },
    insight: "不是每笔支出都能等打折。有些设备坏了，就会直接从储备里拿钱。",
  },
  {
    id: "wedding_gift",
    title: "集中人情往来",
    category: "one_time_cost",
    description: "这个月婚礼、满月和探望集中出现，人情往来一次性支出 3200 元。",
    effect: { type: "change_savings", amount: -3200 },
    insight: "人情支出很难完全预算，但它确实会占用现金储备。",
  },
  {
    id: "pipe_leak",
    title: "家里漏水维修",
    category: "one_time_cost",
    description: "家中水管或龙头漏水，需要上门维修，一次性支出 800 元。",
    effect: { type: "change_savings", amount: -800 },
    insight: "生活里的小故障不会毁掉一局，但会提醒你：现金储备也负责处理这些琐碎意外。",
  },
  {
    id: "salary_cut",
    title: "公司业务调整",
    category: "income_down",
    description: "公司业务调整，你的收入先下降 30%。什么时候恢复，公司没有给明确时间。",
    effect: {
      type: "add_uncertain_active_effect",
      target: "income_percent",
      amount: -0.3,
      minMonths: 2,
      recoveryChance: 0.25,
      maxMonths: 12,
      recoveryText: "公司业务逐步恢复，你的收入回到原来的水平。",
    },
    insight: "收入打折时，支出通常不会跟着打折。真正有压力的不是降薪本身，而是不知道它会持续多久。",
  },
  {
    id: "bonus_cancelled",
    title: "绩效奖金缩水",
    category: "income_down",
    description: "这个月绩效和项目奖金都不理想，工资正常发放，但本月收入减少约 25%。",
    effect: { type: "one_month_income_percent", amount: -0.25 },
    insight: "底薪还在，浮动奖金没来。把不确定收入当成确定收入时，地图会突然变窄。",
  },
  {
    id: "project_delay",
    title: "项目延期回款",
    category: "income_down",
    description: "项目延期回款，本月收入减少 50%。",
    effect: { type: "one_month_income_percent", amount: -0.5 },
    insight: "回款晚到不是没有收入，但账单不会一起等。自由度越高，缓冲也要越厚。",
  },
  {
    id: "temporary_unemployment",
    title: "短期失业",
    category: "income_down",
    description: "你暂时失去工作收入，收入归零，持续 2 个月。",
    effect: { type: "add_active_effect", target: "income_percent", amount: -1, duration: 2 },
    insight: "短期失业是地图上的浓雾区。储备不是赢分道具，是让你慢慢找出口的氧气。",
  },
  {
    id: "commission_slowdown",
    title: "提成到账变慢",
    category: "income_down",
    description: "客户付款周期拉长，本月提成少到账，本月收入减少约 25%。",
    effect: { type: "one_month_income_percent", amount: -0.25 },
    insight: "收入不是没有，只是晚到。现金流最怕的有时候不是少，而是错位。",
  },
  {
    id: "unpaid_leave",
    title: "临时无薪假",
    category: "income_down",
    description: "因为家庭安排，你本月请了几天无薪假，收入减少约 18%。",
    effect: { type: "one_month_income_percent", amount: -0.18 },
    insight: "时间被家庭拿走一部分，收入也会跟着少一块。",
  },
  {
    id: "client_budget_cut",
    title: "客户预算收缩",
    category: "income_down",
    description: "合作客户预算收缩，你的收入下降 20%，持续时间还不确定。",
    effect: {
      type: "add_uncertain_active_effect",
      target: "income_percent",
      amount: -0.2,
      minMonths: 2,
      recoveryChance: 0.3,
      maxMonths: 8,
      recoveryText: "客户预算恢复，你的收入回到原来的水平。",
    },
    insight: "外部预算一收紧，个人现金流也会被牵动。未知期限才是压力来源。",
  },
  {
    id: "year_end_bonus",
    title: "年终奖到账",
    category: "positive",
    description: "年终奖到账，现金储备增加约 1 个月收入。",
    effect: { type: "change_savings_by_income_percent", amount: 1 },
    insight: "一笔奖金到账，像地图上捡到补给包。怎么用，会影响后面几格的底气。",
  },
  {
    id: "side_income",
    title: "副业收入",
    category: "positive",
    description: "本月副业收入增加，约等于本月收入增加 20%。",
    effect: { type: "one_month_income_percent", amount: 0.2 },
    insight: "副业收入不一定每月都有，但它出现时，能给主线现金流一点喘息。",
  },
  {
    id: "spending_control",
    title: "控制消费成功",
    category: "positive",
    description: "你主动控制消费，本月支出减少约 12%。",
    effect: { type: "one_month_expense_percent", amount: -0.12 },
    insight: "少花的 3000 元不会发光，但它会安静地把安全垫垫高一点。",
  },
  {
    id: "tax_refund",
    title: "退税或补贴到账",
    category: "positive",
    description: "退税或补贴到账，现金储备增加 8000 元。",
    effect: { type: "change_savings", amount: 8000 },
    insight: "这笔钱像迟来的补给。先修安全垫，后面的地图会好走不少。",
  },
  {
    id: "freelance_referral",
    title: "朋友介绍兼职单",
    category: "positive",
    description: "朋友介绍了一笔兼职单，本月收入增加约 25%。",
    effect: { type: "one_month_income_percent", amount: 0.25 },
    insight: "偶然出现的收入很提气，但它更适合修补缓冲，而不是立刻放大支出。",
  },
  {
    id: "sell_unused",
    title: "闲置物品卖出",
    category: "positive",
    description: "你清理闲置物品，现金储备增加 1200 元。",
    effect: { type: "change_savings", amount: 1200 },
    insight: "有些现金其实躺在角落里，只是需要你把它翻出来。",
  },
  {
    id: "subscription_cleanup",
    title: "取消闲置订阅",
    category: "positive",
    description: "你清理了几个很少使用的订阅，常规月支出减少 600 元。",
    effect: { type: "add_active_effect", target: "expense", amount: -600, duration: 999 },
    insight: "现金流改善有时候不是赚更多，而是让漏水的地方少一点。",
  },
  {
    id: "minor_illness",
    title: "自己生病休养",
    category: "health_risk",
    description: "你因为身体原因休养，本月收入减少 30%，同时医疗支出增加 5000 元。",
    effect: {
      type: "compound",
      effects: [
        { type: "one_month_income_percent", amount: -0.3 },
        { type: "change_savings", amount: -5000 },
      ],
    },
    insight: "生病最麻烦的地方，是收入和支出会同时朝不友好的方向动。",
  },
  {
    id: "family_care",
    title: "照顾家人",
    category: "health_risk",
    description: "你需要请假照顾家人，本月收入减少约 25%。",
    effect: { type: "one_month_income_percent", amount: -0.25 },
    insight: "照顾家人不是选择题，但现金流会把这段时间真实记下来。",
  },
  {
    id: "dental_cost",
    title: "牙齿治疗",
    category: "health_risk",
    description: "你进行牙齿治疗，一次性支出 6000 元。",
    effect: { type: "change_savings", amount: -6000 },
    insight: "牙齿平时不说话，一开口就是账单。",
  },
  {
    id: "insurance_gap",
    title: "医保报销后的自付账单",
    category: "health_risk",
    description: "一次治疗后，医保已经报销了一部分，但仍有 15000 元需要自己支付。",
    effect: { type: "change_savings", amount: -15000 },
    insight: "医保能挡住一部分风，但不一定挡住全部。现金储备和保障配置，都值得被认真看一眼。",
  },
  {
    id: "child_fever",
    title: "孩子反复发烧",
    category: "health_risk",
    description: "孩子反复发烧，你本月请假照顾并支出检查费用，收入减少约 15%，现金储备减少 2500 元。",
    effect: {
      type: "compound",
      effects: [
        { type: "one_month_income_percent", amount: -0.15 },
        { type: "change_savings", amount: -2500 },
      ],
    },
    insight: "家庭健康事件常常不是一张账单，而是一串临时安排。",
  },
  {
    id: "sports_injury",
    title: "运动受伤",
    category: "health_risk",
    description: "运动受伤后需要检查和康复，一次性支出 6500 元。",
    effect: { type: "change_savings", amount: -6500 },
    insight: "健康支出不一定巨大，但出现得很突然。",
  },
  {
    id: "insurance_review_choice",
    title: "检查保障配置",
    category: "choice",
    description: "你准备检查自己的保障配置。可以花一点钱补齐基础保障，也可以先不调整。",
    choices: [
      {
        label: "补齐基础保障",
        resultText: "你每月增加 900 元保障支出。后续遇到部分健康风险时，可减少一次性储备损失。",
        effect: { type: "start_protection_plan", monthlyAmount: 900, duration: 12, coverageRate: 0.5, maxReduction: 20000 },
      },
      {
        label: "先不调整",
        resultText: "你暂时保留现金储备，不新增固定支出。",
        effect: { type: "none" },
      },
    ],
    insight: "保障配置不是为了赢一局游戏，而是为了让某些坏牌不至于直接打穿储备。",
  },
  {
    id: "rent_or_commute_choice",
    title: "离公司近一点",
    category: "choice",
    description: "你在考虑换到离公司更近的住处。通勤会轻松，但房租会上升。",
    choices: [
      {
        label: "搬近一点",
        resultText: "你选择缩短通勤，常规月支出增加 1800 元；三个月后精力恢复，常规月收入增加 1200 元。",
        effect: {
          type: "compound",
          effects: [
            { type: "add_active_effect", target: "expense", amount: 1800, duration: 999 },
            {
              type: "schedule_active_effect",
              id: "rent_commute_income_boost",
              triggerDelay: 3,
              target: "income",
              amount: 1200,
              duration: 999,
              title: "搬近后的精力恢复",
              message: "住得离公司近一点后，你把通勤时间换回了精力，开始承接更好的工作机会。",
            },
          ],
        },
      },
      {
        label: "暂时不搬",
        resultText: "你继续承受较长通勤，短期省下房租，但精力被通勤消耗，常规月收入减少 1000 元。",
        effect: { type: "add_active_effect", target: "income", amount: -1000, duration: 999 },
      },
    ],
    insight: "搬近一点短期看更贵，但如果精力能换回更好的收入，长期可能反而更划算。",
  },
  {
    id: "family_trip_choice",
    title: "带家人短途旅行",
    category: "choice",
    description: "你想带家人出去放松两天。可以现在就去，也可以暂时推迟。",
    choices: [
      {
        label: "安排旅行",
        resultText: "你花 5800 元安排了一次短途旅行，现金储备减少，但家庭压力得到释放。",
        effect: { type: "change_savings", amount: -5800 },
      },
      {
        label: "暂时推迟",
        resultText: "你保留现金储备，但临时取消行程损失了一些订金。",
        effect: { type: "change_savings", amount: -1000 },
      },
    ],
    insight: "娱乐支出不是坏牌。问题在于，它要和现金储备一起排队。",
  },
  {
    id: "kids_theme_park",
    title: "带孩子去游乐场",
    category: "one_time_cost",
    description: "周末带孩子去游乐场，门票、交通和餐饮一次性支出 1200 元。",
    effect: { type: "change_savings", amount: -1200 },
    insight: "生活里的快乐也会花钱，但它不是财务错误，只是需要被看见。",
  },
  {
    id: "movie_weekend",
    title: "周末看电影聚餐",
    category: "one_time_cost",
    description: "你和家人朋友看电影、简单聚餐，一次性支出 600 元。",
    effect: { type: "change_savings", amount: -600 },
    insight: "小额娱乐不会击穿现金流，但频率会决定它是不是变成固定地形。",
  },
  {
    id: "hobby_class",
    title: "报名兴趣课程",
    category: "choice",
    group: "interest",
    description: "你想报名一个兴趣课程，让生活不只是工作和账单。课程费用 1800 元。",
    choices: [
      {
        label: "报名",
        resultText: "你支付 1800 元报名课程，现金储备减少。",
        effect: { type: "change_savings", amount: -1800 },
      },
      {
        label: "先等等",
        resultText: "你先不报名，现金流暂时不变。",
        effect: { type: "none" },
      },
    ],
    insight: "长期生活不能只靠压缩支出。偶尔给自己充电，也是一种维持。",
  },
  {
    id: "fishing_gear_choice",
    title: "入门钓鱼装备",
    category: "choice",
    group: "interest",
    description: "朋友约你周末去钓鱼。想认真玩的话，需要买一套入门装备。",
    choices: [
      {
        label: "买一套装备",
        resultText: "你花 1200 元买了基础装备，现金储备减少。",
        effect: { type: "change_savings", amount: -1200 },
      },
      {
        label: "先借朋友的",
        resultText: "你先借装备体验一次，只承担交通和餐食。",
        effect: { type: "change_savings", amount: -300 },
      },
    ],
    insight: "爱好不是错误，关键是别让一次尝鲜直接变成一串没想清楚的支出。",
  },
  {
    id: "outdoor_hike_choice",
    title: "周末户外徒步",
    category: "choice",
    group: "interest",
    description: "你想参加一次周末户外徒步，报名、装备补充和交通都要花钱。",
    choices: [
      {
        label: "参加徒步",
        resultText: "你支付 1500 元参加徒步，现金储备减少。",
        effect: { type: "change_savings", amount: -1500 },
      },
      {
        label: "城市公园走走",
        resultText: "你选择低成本放松，本月现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "恢复精力也值得花钱。只是花多少，要和当下的安全垫商量一下。",
  },
  {
    id: "yoga_membership_choice",
    title: "瑜伽体验课",
    category: "choice",
    group: "interest",
    description: "你试了一节瑜伽课，想买一个 3 个月的小课包。",
    choices: [
      {
        label: "买小课包",
        resultText: "你每月增加 600 元运动支出，持续 3 个月。",
        effect: { type: "add_active_effect", target: "expense", amount: 600, duration: 3 },
      },
      {
        label: "先跟练视频",
        resultText: "你暂时不买课包，现金流不变。",
        effect: { type: "none" },
      },
    ],
    insight: "持续型兴趣支出最需要提前想清楚，因为它会跟着你走好几个月。",
  },
  {
    id: "index_dca_choice",
    title: "低估区域的定投机会",
    category: "choice",
    description: "你关注的某个宽基指数进入相对低估区域。",
    choices: [
      {
        label: "开始定投",
        resultText: "你开启了每月 2000 元的长期定投计划。",
        effect: { type: "start_dca_plan", monthlyAmount: 2000 },
      },
      {
        label: "暂不定投",
        resultText: "你选择先观察，不改变本月和未来现金流。",
        effect: { type: "none" },
      },
      {
        label: "先建立现金储备",
        resultText: "你决定先压缩可消费支出 2000 元，持续 6 个月，把安全垫垫厚一点。",
        effect: { type: "add_active_effect", target: "expense", amount: -2000, duration: 6 },
      },
    ],
    insight: "本月选择已经记录，后续可能出现新的市场状态。",
  },
  {
    id: "career_course",
    title: "职业提升课程",
    category: "choice",
    description: "你看到一个职业提升课程，费用 8000 元，可能帮助你未来提升收入。是否报名？",
    choices: [
      {
        label: "报名",
        resultText: "你支付 8000 元报名课程，未来可能获得收入提升机会。",
        effect: { type: "career_course_plan", cost: 8000 },
      },
      {
        label: "暂不报名",
        resultText: "你选择保留现金储备，暂不报名。",
        effect: { type: "none" },
      },
    ],
    insight: "有些钱花出去像播种，但播种也要先保证这个月的饭碗稳。",
  },
  {
    id: "buy_car_choice",
    title: "是否换车",
    category: "choice",
    description: "现在换车可以改善通勤，但会减少储备并增加月供。是否换车？",
    choices: [
      {
        label: "换车",
        resultText: "你换了一辆车，现金储备减少 50000 元，每月支出增加 2500 元。",
        effect: { type: "buy_car" },
      },
      {
        label: "暂不换车",
        resultText: "你选择暂不换车，保留现金储备。",
        effect: { type: "none" },
      },
    ],
    insight: "换车不是只付一次钱，它会把未来几个月的地图也一起改掉。",
  },
  {
    id: "emergency_fund_choice",
    title: "建立应急储备计划",
    category: "choice",
    description: "你决定是否从这个月开始，压缩一部分可选消费支出作为应急储备。",
    choices: [
      {
        label: "开始储备",
        resultText: "你开始压缩可选消费支出，常规月支出减少约 15%，持续 6 个月。",
        effect: { type: "add_active_effect", target: "expense_percent", amount: -0.15, duration: 6 },
      },
      {
        label: "暂不调整",
        resultText: "你暂时保持原有消费习惯。",
        effect: { type: "none" },
      },
    ],
    insight: "储备不是一夜长出来的。它更像每天给安全垫多塞一点棉花。",
  },
];
